rhochgraf21/Constitution

- constitution.tex
Check one:
Fixed "simply majority vote" to "simple majority vote".
> fixed simple majority vote from rtp vote

- constitution.tex
Check one:
This PR adds an anti-hazing/anti-discrimination article. 
Resolves #1
> Resolve #1 Add Anti-Discrimination Clause

- constitution.tex
Check one:
This PR removes the ability for Judicial Boards to arbitrarily violate the privacy of House members.
Resolves #14
> Resolve #14 Potential Issue with Privacy in Judicials

- constitution.tex
Check one:
Resolves #95 by moving 2.B (Closed Executive Board) to after 2.C (Responsibilities of the Executive Board).
> Resolves #95 Move Section 2.B

- constitution.tex
> Resolve #91 Remove unnecessary colon

- constitution.tex
> Resolve #87 3.A Remove First Sentence

- constitution.tex
> Resolve #94 Remove list of directors

- constitution.tex
> Resolve #90 - Change right to privilege

- constitution.tex
> Resolve #93 Remove last sentence

- constitution.tex
> Resolve #77 Change shall be to is

- README.md
Check one:
Resolves #53 by updating the README to remove references to the bylaws.
> Resolves #53 Fix README.md

- constitution.tex
> Resolve #80 Remove 2.A

- constitution.tex
Check one:
Resolves #44 
Namely, this removes point (d) from the description.
> Update #44 Review Responsibilities of the Research and Development Director

- constitution.tex
> 2.B Removed last line

- constitution.tex
> Resolve #84 Condense 2.C.2

- constitution.tex
Check one:
Resolve #58 by changing wording of section headers to make them much easier to read.
> Resolve #58 Reduce number of words

- constitution.tex
Check one:
Condensed 4.F into one section about leave of absence that references the RIT policy for leave of absence
> Resolve #71 Condense Leave of Absence

- constitution.tex
> Resolve #78 - change reslife to student development

- constitution.tex
Check one:
No meaning was changed, reworded 5.D.1.D to make it less confusing and remove unnecessary words/lines.
> Reword 5.D.1.D to improve clarity

- constitution.tex
Check one:
Fixed bulleted list in 4.B.4 based on discussion during Tuesday's meeting
> Resolve #66 Update list of Active Member Priveleges

- constitution.tex
Check one:
Resolve #41 
Namely, this changes wording found in subsection (c) and combines subsections (c) and (d).
> Update #41 Review Responsibilities of the Social Director

- constitution.tex
Check one:
Wrote a first draft of an abbreviations section. I intend to bring this up for discussion during tomorrows meeting (9/26/23).
> Resolve #51 Add abbreviations section

- constitution.tex
Check one:
This PR explicitly defines what it means to be a voting member of E-Board.
> Clarify voting member of E-Board

- constitution.tex
Check one:
Reordered dues breakdown table to be in descending order
> Resolve #129 Reorder Dues Table

- constitution.tex
Check one:
Deleted a few lines at the end that were just reiteration of information above, general rewording to make the section smaller and get the same point across.
> Reword 5.D.1.B.1 since it was really long and repeated a lot of the same information.

- constitution.tex
> Updated qualifications of an RTP

- constitution.tex
Check one:
Added point about communicating with ITS, as per conversation with joe
> Resolves #46 - Review Responsibilities of OpComm Director

- constitution.tex
Check one:
Made it so the intro process is more concretely defined, rather than just stating the purpose of it
> 134 Define intro process

- constitution.tex
Reverts rhochgraf21/Constitution#96
> Revert "Resolve #72 Give Ad Hocs Their Own Section"

- constitution.tex
Check one:
Added requested changes to the responsibilities of the chairperson.
> 5.C.2 Responsibilities of the Chairperson

- Dockerfile
- nginx.conf
Check one:
- Use official nginx-unprivileged image instead of one in Galen's account
- Add line to config to work on OKD
> Better NGINX Setup

- constitution.tex
Check one:
allow for non-semantic changes to the code of conduct by RTPs
> non semantic code of conduct changes

- constitution.tex
Check one:
This PR aims to fix the issue with the resignation of a Chairperson in #38.
> Clarify Resignation of Chair

- constitution.tex
Check one:
Fixed various grammar and punctuation issues throughout the document.
> Fixed grammar + punctuation issues

- constitution.tex
Check one:
This PR fixes grammar, makes formatting throughout the document, and makes an organization change. This organization change creates a section in Article VI (General Operations of the House) to contain all general points about any Evaluations process. Specifically, this new section contains the text that requires the Evals Director to read the relevant sections of the document and the appeals process surrounding our Evaluations processes.
> Grammar, Formatting, and Organization Fixes

- constitution.tex
Check one:
I added Socials back into the abbreviations
> 300 i deleted socials in the table of abbreviations

- .gitignore
> 227 - PDFs are an L

- constitution.tex
Check one:
I changed 6.A.2.A and 6.C.1 to reduce words and the ability for members to cap other members
> 226 small wording changes

- constitution.tex
Check one:
Reverts Leave of Absence language.
> Revert Leave of Absence
