rhochgraf21/Constitution

constitution.tex

Check one:
Updated section 5.C.1.F to reflect current practice

fixed major projects being presented to eboard by evals

---

constitution.tex

Check one:
Matches formatting in 6.B.5 to improve clarity and match formatting of surrounding references to Chair of the Vote.
Resolves #9

Resolve #9 Batch Vote Chair

---

constitution.tex

Check one:
Removed section formerly 6.C.5, Three Tiered vote which resolves #3.

Removed Section formerly 6.C.5, Three Tiered Vote

---

constitution.tex

Check one:
Replaced parenthetical with slightly less ambiguous language to resolve #11.

Resolve #11 Quorum Definition Unnecessarily Broad

---

constitution.tex

Check one:
Removed reference to full membership in 5.D.2.B.2 subsection (b)

Resolve #49 Full Membership

---

constitution.tex

Check one:
Section formerly 5.D.2.A.4.C, Alternate Housing, is removed to reflect current practice and comply with RIT Housing, which resolves #2.

Removed Section formerly 5.D.2.A.4.C, Alternate Housing, which violates RIT housing

---

constitution.tex

Check one:
This PR proposes a change to 5.D.1.C, namely by removing all calculations and clarifying where dues from on-floor and off-floor members go.

Resolve #7 Fix Financial Information/Calculations in 5.D.1.C

---

constitution.tex

Check one:
Remove all references to a physical packet document
resolves #50

Resolve #50 Packet Document

---

constitution.tex

Check one:
Resolves #85 by merging 2.C.3 and 2.C.4 into one section for Maintainer Resignations.

Resolves #85 Merge 2.C.3 and 2.C.4

---

constitution.tex

Check one:
Resolves #83 by allowing Maintainers to be Alumni in bad standing.

Resolves #83 Allow Maintainers to be Alumni in Bad Standing

---

constitution.tex

Resolve #89 - replace qualifying with alumni in good standing

---

constitution.tex

Check one:
Resolves #86 by adding a proposed quorum requirement to vote on Maintainer nominations.

Resolves #86 Add Quorum Requirement for Maintainer Nominations

---

README.md
constitution.tex

Check one:
Alumni now always have a housing status, which will be kept when returning to active membership. When an active member enters alumni membership with good standing, they keep their current housing status. If they enter bad standing, they are automatically assigned Off-Floor status.

Resolve #29 Alumni Housing Status

---

constitution.tex

Check one:
Intended to supplement discussion on combining Honorary and Advisory Memberships.
- Both Honorary and Advisory members are selected via 2/3 votes
- Honorary and Advisory Members share the selection, priveleges, evaluations, resignations, and term 
subsections.

Resolve #22 Combine Honorary and Advisory Members

---

constitution.tex

Check one:
Resolves #67 by removing last paragraph about voting exemptions for Active members on co-op in 4.B.4.

Resolve #67 4.B.4 Remove Last Paragraph

---

constitution.tex

…o members has to be present
Check one:
changed one line so that only one of the two members of the dual has to be present. Made this section reflect current practice.

Changed last bullet point in 5.F.1 to reflect best practice

---

constitution.tex

Check one:
Resolves issue #36 by replacing both references to Semi-Annual Membership Evaluations found in 5.C.3(d) and 5.D.2.C.

Resolve #36 Membership Evaluations Only Occur Once A Year

---

constitution.tex

Check one:
removed an extra newline before a line break to fix existing compilation errors

Removed extra newline that caused document to fail to compile

---

constitution.tex

Check one:
This PR moves the responsibility of overseeing to organization of Open Houses and similar events from Evals to PR.

Update Open House Responsibilities for Evals and PR

---

constitution.tex

Check one:
1 - moving Packet, Introductory Evaluations, Membership Evaluations, and Selection Processes into the Membership section
2 - moving operations of the Evaluations/Financial directorships into "General Operations of the House"
3 - moving maintainers and RTPs under "Officers of the House"

resolve #13 reorganize sections

---

constitution.tex

Check one:
Resolves #72 by adding in a section for Ad Hoc Directorships in Article 5 and refactoring some content around it.

Resolve #72 Give Ad Hocs Their Own Section

---

constitution.tex

Check one:
Resolves #127  by rewording 5.D.1.B to reflect the fact that dues are equivalent for on-floor and off-floor members.

Resolves #127 Condense 5.D.1.B

---

constitution.tex

Check one:
Combined 5.E.1 and 5.E.2 and created a bullet for chair and evals instead of a whole different redundant section.

Combined 5.E.1 and 5.E.2

---

constitution.tex

Check one:
Added a sentence to clarify what the status of a member is during a conditional.

5.D.2.C.1.B Clarified Membership Status During Conditional

---

constitution.tex

Check one:
removes 'note' and 'additional note' from 5.D.2.B.1 and 5.D.2.B.2, (4.A.2.A.1 and .2)
those notes are now under 4.A.2.A

136 removing dry notes

---

constitution.tex

Check one:
Fixes the ordering in the budget allocation table in 6.A.3 by the attributes decided earlier in the year to account for abbreviations.
As a recap, they are first sorted by budget amount then length of the name used in the table, with Accumulated always as the last row.

Reorganize Budget Allocation Table in 6.A.3

---

constitution.tex

Check one:
I removed "Candidates must have at least one full semester of Active Membership"

I removed the two lines that are illegal
